###########
# site.title, site.url, site.author.name

title:   'Flix Capacitor'
url:     'https://flixcapacitor.github.io/test'
author:
  name:  'Joshua Wille, PhD'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /test  
url:  'https://flixcapacitor.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

